parallel: true
format: progress
plugins:
  - standard-rails
ignore:
  - test/**/*
  - config/**/*
  - app/mailers/*
  - spec/rails_helper.rb
  - spec/spec_helper.rb
overrides:
  Rails/RedundantPresenceValidationOnBelongsTo:
    Enabled: false
    
